const agentsData = [
  {
    id: 1,
    name: "Dipesh H Vora Estate agent",
    address: "Shop No.47, Tulsi Chambers, Umarshi Bappa Chowk, Mumbai",
    rating: 4.7,
    reviews: 817,
    listings: 147,
    areas: ["Navi Mumbai", "Pune", "Ratnagiri", "Thane", "Raigad"],
    services: ["Buy", "Sell", "Rent/PG"],
    imageUrl: "/1.jpg",
  },
  {
    id: 2,
    name: "square feet",
    address: "Jogeshwari, Mumbai",
    rating: 5,
    reviews: 48,
    listings: 0,
    areas: ["Kelwa Palghar", "Thane"],
    services: ["Buy", "Sell", "Rent/PG"],
    imageUrl: "/2.jpg",
  },
  {
    id: 3,
    name: "A-square real state consultant",
    address: "Shop No. 3, Florida, Shastrinagar, Near Lokhandwala Circle",
    rating: 4.5,
    reviews: 114,
    listings: 10,
    areas: [
      "Byculla",
      "Juhu",
      "Jogeshwari",
      "Vile Parle",
      "Malad East",
      "Malad West",
    ],
    services: ["Buy", "Sell", "Rent/PG"],
    imageUrl: "/3.avif",
  },
  {
    id: 4,
    name: "Shankar real estate agency",
    address:
      "311 Room Number Aasara Apartment Hanuman Nagar, Nalasopara West, Mumbai",
    rating: 4.2,
    reviews: 49,
    listings: 0,
    areas: ["Vasai", "Vasai East", "Vasai West"],
    services: ["Buy", "Sell", "Rent/PG"],
    imageUrl: "/4.jpeg",
  },
  {
    id: 5,
    name: "Pritesh State Agent",
    address: "Neral, Mumbai",
    rating: 5,
    reviews: 82,
    listings: 2,
    areas: ["Neral"],
    services: ["Buy", "Sell", "Rent/PG"],
    imageUrl: "/5.avif",
  },
];

export default agentsData;
